name: Production Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up WARP
        uses: fscarmen/warp-on-actions@v1.1
        with:
          stack: dual

      - name: testing ipv6 for command
        run: |
          curl -m 9 --ipv6 --verbose https://google.com

      - name: Production Deployment
        uses: appleboy/ssh-action@v1.2.2
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          protocol: tcp6
          script: |
            export NVM_DIR="$HOME/.nvm"
            export PATH="$NVM_DIR/versions/node/v22.17.0/bin:$PATH"

            cd /root/age-detection-fe
            git pull origin main
            npm install
            npm run build
            pm2 reload ecosystem.config.js --env production || pm2 start ecosystem.config.js --env production
